### PR TITLE
add spec test to not use version when comparing

### PR DESCRIPTION
**Pull request by xabbuh**

### CODE REVIEW

**Comment by xabbuh** [comment]
@Lctrs What do you think? This is not mentioned anywhere explicitly, but seems logical to me.

**Comment by Lctrs** [comment]
In fact, it's mentioned in the spec (see the bold sentence below) : 
> Note: The requirement for the "version" property to contain the value 1.0.0, rather than the latest patch version is deliberate since Statements in any version of 1.0.x conform to the 1.0.0 data model. **In fact, a single Statement may be included in multiple requests over time, each following a different patch version of the specification.** The patch version of the specification being followed can be determined from the "X-Experience-API-Version" header being used in each request.

So, I think we should at least consider 2 statements equal if their patch versions differ.
Or maybe we can see beyond that and don't do this check at all. After all, 2 statements can be equals even if they are not at the same version of the spec.

**Comment by Lctrs** [comment]
PS : I just noticed that my last sentence can be interpreted as a little attack towards you. It's not. My english is far from perfect so my phrasing can be a little clumsy sometimes. :)

**Comment by xabbuh** [comment]
To me that sentence is more about the statement conforming to any client requesting it in the future (no matter which version they support). However, I checked how this is handled in other libraries and I didn't see that they do compare the version. Thus let's not start with it here, but just add a test that makes it explicit that we don't care about differing versions.

**Comment by Lctrs** [comment]
👍

**Pull request merged**
