### PR TITLE
Deprecate constructing State with anything other than Agent as 2nd argument

### LINKED ISSUE #49: $actor property of State model should be an Agent
instead of an Actor (= Agent or Group).

### PR DESCRIPTION
**Pull request by Lctrs**
Close #49.

### CODE REVIEW

**Comment by xabbuh** [comment]
Can you also add an entry to the changelog?

**Comment by xabbuh** [comment]
After thinking about this again I think we should do the following:

* trigger a deprecation in the constructor when an `Actor` that is no `Agent` is passed
* deprecate the `getActor()` method
* add the `getAgent()` method

We can then merge this into the `1.x` branch. What do you think?

**Comment by Lctrs** [comment]
@xabbuh Done. Any feedback on this ?

**Comment by Lctrs** [comment]
@xabbuh Should I also change the version from `1.1.1` to `1.2` as in #55 here ?

**Comment by xabbuh** [comment]
@Lctrs Oh, yes indeed please.

**Comment by xabbuh** [comment]
Thank you @Lctrs.

**Pull request closed without merging**
